config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :tweets
  root  'tweets#index'
  # resources :users, only: [:show]
    # get   'tweets'      =>  'tweets#index'
    # get   'tweets/new'  =>  'tweets#new'
    # post  'tweets'      =>  'tweets#create'
    # delete  'tweets/:id'  => 'tweets#destroy'
    # get   'users/:id'  =>  'users#show'
    # get 'tweets/:id/edit' =>'tweets#edit'
    # patch   'tweets/:id'  => 'tweets#update'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  
  def index
    @tweets = Tweet.all.order("id DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
    redirect_to tweets_path
  end
  
  def show
    @nickname = current_user.nickname
    @tweet = Tweet.find(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :text)
  end
   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def show
  # @nickname = current_user.nickname
  # @tweets = Tweet.where(user_id: current_user.id).order("created_at DESC")
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
          
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <% @tweets.each do |tweet| %>
      <div class="card">
       <div class="card-panel light-green">
        <div class="card-title">
          <span class="card-title">今日の出来事は？</span>
        </div>
        <div class="card-content">
          <h1><%= tweet.user.nickname %></h1>
          <%= tweet.text %>
          <div class="card-action">
          <% if user_signed_in? %>
            <%= link_to "詳細", "/tweets/#{tweet.id}", method: :get, class: 'btn btn-edit' %>
            <%= link_to "削除", "/tweets/#{tweet.id}", method: :delete, class: 'btn btn-danger', data: { confirm: '削除します。よろしいですか' } %>
            <%= link_to "編集", "/tweets/#{tweet.id}/edit", method: :get, class: 'btn btn-edit' %>
          <% else %>
            ログインしてね
          <% end %>
          </div> 
        </div>
       </div>
      </div>
    <% end %>
  </div>
</div>

    

app/views/tweets/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
<nav class="green lighten-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">日記</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "戻る","/tweets", method: :get %></li>
      <% else %>
        <li><%= link_to "え、くんの？","/users/sign_in", method: :get %></li>
        <li><%= link_to "アカウント欲しい？",new_user_registration_path, method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="contents row">
<h3>
      編集しよう
</h3>
<%= form_for @tweet, url: tweet_path(params[:id]) do |f| %>

 

  <div class="field">
    <%= f.label :text, "思ったこと" %>
    <%= f.text_field :text %>
  </div>

    <div class="field">
    <%= f.label :submit, "編集する" %>
    <%= f.submit "編集"%>
   </div>
  </div>
  
  
<% end %>
</div>

app/views/tweets/index.html.erb
<nav class="green lighten-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">日記</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "書く","/tweets/new", method: :get %></li>
      <% else %>
        <li><%= link_to "ろぐいん","/users/sign_in", method: :get %></li>
        <li><%= link_to "作る",new_user_registration_path, method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>
  
 <%=render :partial => "tweet" %>
<script type="text/javascript" src="./app.js"></script>

app/views/tweets/new.html.erb
<nav class="green lighten-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">日記</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "戻る","/tweets", method: :get %></li>
      <% else %>
        <li><%= link_to "え、くんの？","/users/sign_in", method: :get %></li>
        <li><%= link_to "アカウント欲しい？",new_user_registration_path, method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>


<div class="contents row">
　<div class="minihead">
    <h3>
          投稿
    </h3>
  </div class="minihead">
  <%= form_for @tweet,url: tweets_path do |f| %>
    <div class="field">
      <%= f.label :text, "思ったこと" %>
      <%= f.text_field :text %>
    </div>

    <div class="field">
    <%= f.label :submit, "投稿" %>
    <%= f.submit "投稿する"%>
    </div>
  </div>
  <% end %>
</div>

app/views/tweets/show.html.erb
<nav class="green lighten-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">日記</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "一覧に戻る","/tweets", method: :get %></li>
      <% else %>
        <li><%= link_to "え、くんの？","/users/sign_in", method: :get %></li>
        <li><%= link_to "アカウント欲しい？",new_user_registration_path, method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="row">
  <div class="col s6 offset-s3">
    <div class="card">
    <%= @tweet.text %>
      <div class="card-content">
        <div class="card-action">
        <% if user_signed_in? %>
           <div class="col s6 offset-s10">
          <%= link_to "編集", "/tweets/#{@tweet.id}/edit", method: :get, class: 'btn btn-edit' %>
           </div>
        <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新終わり
      </h3>
      <a class="btn" href="/">戻る</a>
    </div>
  </div>